/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as OptimizationRouteImport } from './routes/optimization'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as WellDynamicsRouteImport } from './routes/well-dynamics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationRoute = OptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const WellDynamicsRoute = WellDynamicsRouteImport.update({
  id: '/well-dynamics',
  path: '/well-dynamics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/optimization': typeof OptimizationRoute
  '/reports': typeof ReportsRoute
  '/well-dynamics': typeof WellDynamicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/optimization': typeof OptimizationRoute
  '/reports': typeof ReportsRoute
  '/well-dynamics': typeof WellDynamicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/optimization': typeof OptimizationRoute
  '/reports': typeof ReportsRoute
  '/well-dynamics': typeof WellDynamicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/live-monitoring' | '/optimization' | '/reports' | '/well-dynamics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live-monitoring' | '/optimization' | '/reports' | '/well-dynamics'
  id:
    | '__root__'
    | '/'
    | '/live-monitoring'
    | '/optimization'
    | '/reports'
    | '/well-dynamics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  OptimizationRoute: typeof OptimizationRoute
  ReportsRoute: typeof ReportsRoute
  WellDynamicsRoute: typeof WellDynamicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimization': {
      id: '/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof OptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-dynamics': {
      id: '/well-dynamics'
      path: '/well-dynamics'
      fullPath: '/well-dynamics'
      preLoaderRoute: typeof WellDynamicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  OptimizationRoute: OptimizationRoute,
  ReportsRoute: ReportsRoute,
  WellDynamicsRoute: WellDynamicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
